import type { Plugin } from 'vite'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Emits the shop's service worker at build time.
 *
 * Why one is needed at all: without a service worker the browser cannot fetch
 * index.html or the JavaScript chunks when the line is down, so with no
 * internet the owner does not get a degraded till — he gets the browser's
 * "no connection" page and cannot sell at all. Firestore's IndexedDB cache
 * only helps once the app is already running.
 *
 * It is written here rather than pulled from a plugin so there is no extra
 * dependency and nothing hidden: the file below is exactly what ships.
 */

/** Assets that are worth having before they are ever asked for. */
const PRECACHE_EXT = /\.(?:js|css|html|svg|png|webmanifest|woff2?)$/

/**
 * The last thing the till can put on screen.
 *
 * It is inlined into sw.js rather than shipped as a file because the situation
 * it exists for is exactly "the cache does not have what we need" — a fallback
 * that itself has to be fetched or looked up is not a fallback. Both languages
 * are hardcoded: a service worker cannot reach i18next, and this page has to
 * work at the moment nothing else does.
 *
 * It says the one thing the owner actually needs to know at that point, which
 * is that the sales already taken on this machine are not gone. Firestore's
 * queue lives in IndexedDB and is untouched by anything in this file, so
 * "clear browsing data" is the only way to lose it — hence the warning.
 */
const OFFLINE_HTML = `<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hors ligne</title>
<style>
body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px;
background:#faf7f2;color:#1f2933;font-family:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
main{max-width:32rem;text-align:center}
h1{font-size:1.5rem;margin:0 0 .75rem}
p{margin:0 0 1rem;line-height:1.6}
button{font:inherit;padding:.7rem 1.4rem;border:0;border-radius:.6rem;background:#1f6f5c;color:#fff;cursor:pointer}
small{display:block;margin-top:1.5rem;line-height:1.6;opacity:.75}
@media (prefers-color-scheme:dark){body{background:#14181c;color:#e7ecef}}
</style>
</head>
<body>
<main>
<h1>Pas de connexion</h1>
<p>L'application n'a pas pu s'ouvrir : sa copie locale n'est pas disponible sur cet appareil et le réseau ne répond pas.</p>
<p dir="rtl" lang="ar">تعذّر تشغيل التطبيق: النسخة المحليّة غير متوفّرة على هذا الجهاز والشبكة لا تستجيب.</p>
<button onclick="location.reload()">Réessayer &middot; إعادة المحاولة</button>
<small>Les ventes déjà enregistrées sur cet appareil ne sont pas perdues : elles repartiront au retour de la connexion. Ne videz pas les données du navigateur.
<br><span dir="rtl" lang="ar">المبيعات المسجّلة على هذا الجهاز لم تُفقد وسترسل عند عودة الاتصال. لا تحذف بيانات المتصفّح.</span></small>
</main>
</body>
</html>`

function swSource(
  precache: string[],
  version: string,
  entry: string,
  essential: string[],
): string {
  return `/* Generated by scripts/pwa.ts at build time — do not edit by hand. */
const VERSION = '${version}'
const CACHE = 'librairie-' + VERSION
const PRECACHE = ${JSON.stringify(precache, null, 2)}

// The entry script this worker was built alongside, e.g. /assets/index-a1b2c3.js.
// It is the one thing a document claiming to be our shell cannot fake: see
// putShell() for the two failures it rules out.
const ENTRY = ${JSON.stringify(entry)}

/** @see isEssential */
const ESSENTIAL = ${JSON.stringify(essential, null, 2)}

const OFFLINE_HTML = ${jsLiteral(OFFLINE_HTML)}

/** The shell document, under both of the keys it is precached as. */
function isShellUrl(url) {
  return url === '/' || url === '/index.html'
}

/**
 * Everything the app is a blank screen without: the shell plus the entry chunk
 * and what it statically imports. install() treats these as all-or-nothing;
 * everything else — the icon, the manifest, images, and every lazily-loaded
 * route chunk — is best-effort.
 *
 * THIS USED TO BE "ANY .js OR .css", AND THAT WAS TOO WIDE TO BE SAFE. It swept
 * in every lazy route: the dashboard's recharts bundle is the largest file in
 * the build and is needed only by a screen the till never opens. One dropped
 * fetch on it — a first visit over a shop line that flickers for a second —
 * rejected the whole install, the browser discarded the worker, and a machine
 * with no previous worker was left with NO OFFLINE CACHE AT ALL, silently,
 * while the app looked perfectly healthy until the line went down for real.
 *
 * A lazy chunk that is genuinely missing later is already handled properly and
 * visibly: the /assets handler answers 504, React.lazy rejects, and the route
 * error boundary offers a retry on that one page. Losing one screen beats
 * losing the offline cache for all of them.
 */
function isEssential(url) {
  return isShellUrl(url) || ESSENTIAL.indexOf(url) !== -1
}

/** The honest last resort, when there is neither a line nor a cached shell. */
function offlinePage() {
  return new Response(OFFLINE_HTML, {
    // 503 and no-store: this is not the app, and nothing anywhere should keep it.
    status: 503,
    headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' },
  })
}

/**
 * Is this response our own document, or whatever the network in the middle
 * decided to answer with?
 *
 * A captive portal answers the navigation with its login page, a broken deploy
 * answers 404, an overloaded host answers 502. A navigation request carries
 * redirect mode "manual", so a portal that 302s surfaces here as an opaque
 * redirect with status 0 and fails res.ok; a followed redirect on the install
 * fetch fails res.redirected.
 */
function isShell(res) {
  if (!res || !res.ok || res.redirected) return false
  return (res.headers.get('Content-Type') || '').toLowerCase().indexOf('text/html') !== -1
}

/**
 * Stores the shell document, but only if it really is THIS build's index.html.
 *
 * Two distinct failures, one check. The obvious one: the navigation handler
 * used to clone and put whatever came back into the cache as /index.html with
 * no status, redirect or content-type test at all, while activate() below had
 * already deleted the previous cache version. A hotel-wifi login page, a 404 or
 * a 5xx body became the offline shell, and the till then opened in the morning
 * on a portal page and stayed that way until a real line came back.
 *
 * The subtler one: even a perfectly valid index.html from a NEWER deploy does
 * not belong in this cache. This worker precached this build's chunks; a newer
 * shell asks for fingerprinted names this cache does not hold and the server
 * may no longer serve at all, so pairing them hands the shop a shell that
 * cannot boot offline. Requiring the document to mention ENTRY keeps the shell
 * and the chunks in one cache belonging to one build. A new deploy still
 * reaches the shop by the intended route: sw.js changes whenever the CONTENT of
 * any precached file changes, so the new worker installs its own complete cache
 * and waits for the owner to accept it.
 *
 * It is also the only test that catches a captive portal answering 200 with its
 * own HTML at our own URL, which passes every other check in isShell().
 */
function putShell(cache, key, res) {
  if (!isShell(res)) throw new Error('shell refused for ' + key + ': status ' + res.status)
  return res.text().then((body) => {
    if (!isOurBuild(body)) throw new Error('shell at ' + key + ' is not this build')
    // text() consumed the stream, so the stored copy is rebuilt from the string.
    return cache.put(key, shellResponse(body, res))
  })
}

/**
 * A servable, storable copy of a shell document already read into a string.
 *
 * Only the content type is carried over. Content-Encoding and Content-Length
 * describe bytes on the wire that no longer exist once the body has been decoded
 * and re-wrapped, and the status is pinned to 200 because the Response
 * constructor throws on a body with a 204.
 */
function shellResponse(body, res) {
  return new Response(body, {
    status: 200,
    headers: { 'Content-Type': res.headers.get('Content-Type') || 'text/html; charset=utf-8' },
  })
}

/** Is this document the shell this worker was built alongside? */
function isOurBuild(body) {
  // With no ENTRY — a build with no entry chunk, which should not happen — the
  // test cannot be made and the checks in isShell() have to stand on their own.
  return !ENTRY || body.indexOf(ENTRY) !== -1
}

/**
 * A navigation the network answered, read before it is believed.
 *
 * The response looks like HTML and says 200, which is exactly what a captive
 * portal answering every URL with its login form also says. Serving that would
 * replace a working till with a wifi login page, so the body has to name this
 * build (see putShell) before it is either shown or stored; if it does not, the
 * shell precached at install wins. Buffering the document to check costs
 * nothing measurable — it is a couple of kilobytes of HTML whose only job is to
 * pull in the scripts, and the browser could not render a partial one anyway.
 */
function networkShell(res) {
  return res.text().then((body) => {
    // A body can only be used once, so the copy is minted per use.
    const copy = () => shellResponse(body, res)
    if (!isOurBuild(body)) return caches.match('/index.html').then((hit) => hit || copy())
    // Keep the cached shell current for the next cold start with no line. Not
    // awaited: the page must never wait on a cache write.
    caches
      .open(CACHE)
      .then((cache) => cache.put('/index.html', copy()))
      .catch(() => {
        /* the shell already cached is the one that boots; leave it alone */
      })
    return copy()
  })
}

/**
 * Fetches one precached URL and stores it only if the answer can be trusted.
 * Rejects otherwise, and lets the caller decide whether that is fatal.
 */
function precacheOne(cache, url) {
  // cache: 'reload' bypasses the HTTP cache, so a proxy still holding last
  // week's index.html cannot be what gets pinned as this version's shell.
  return fetch(new Request(url, { cache: 'reload' })).then((res) => {
    if (isShellUrl(url)) return putShell(cache, url, res)
    if (!res.ok || res.redirected) {
      throw new Error('precache refused ' + url + ': status ' + res.status)
    }
    return cache.put(url, res)
  })
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => {
      const essential = PRECACHE.filter(isEssential)
      const optional = PRECACHE.filter((url) => !isEssential(url))
      // All or nothing for the shell and the chunks. If one of them cannot be
      // fetched over this line, Promise.all rejects, waitUntil rejects, the
      // browser throws THIS worker away and the previously installed one stays
      // in charge with a cache that is known to be complete — which is the
      // outcome the shop wants. Every add used to carry its own
      // .catch(() => {}) and install resolved regardless, so a worker installed
      // over a flaky line could be missing the till chunk while reporting
      // itself healthy; /assets is cache-first, so React.lazy then rejected
      // offline and the whole tree unmounted to a blank screen with no way back.
      return Promise.all(essential.map((url) => precacheOne(cache, url))).then(() =>
        // A favicon that 404s must never be the reason a shop cannot sell.
        Promise.all(optional.map((url) => precacheOne(cache, url).catch(() => {}))),
      )
    }),
  )
  // Deliberately NO skipWaiting: a new build must not swap the JavaScript under
  // a sale that is halfway through, and one page running chunks from two builds
  // is worse than a page running yesterday's build.
  //
  // What that costs, stated precisely because the comment here used to overstate
  // it: a waiting worker is promoted only once every tab it would control is
  // CLOSED. A reload is not enough. The till's tab is open from morning to
  // night, so on that machine an update never lands on its own — it lands when
  // the owner accepts the banner, which posts SKIP_WAITING below (see
  // src/lib/serviceWorker.ts), or when the browser is closed for the night.
})

self.addEventListener('message', (event) => {
  // The owner's decision, never ours: swapping the worker mid-sale can serve
  // one page chunks from two different builds. src/lib/serviceWorker.ts only
  // sends this from a button the owner presses.
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return

  const url = new URL(req.url)

  // Everything Firebase is left completely alone. Firestore's transport is a
  // long-lived streaming channel with its own offline queue; putting a fetch
  // handler in front of it would at best cache nothing and at worst break the
  // stream and the write queue with it.
  if (url.origin !== self.location.origin) return

  // The page itself: try the network first so a deploy is picked up, and fall
  // back to the cached shell when there is no line. React Router owns the
  // routing once the shell is up, so /caisse and /stock work the same way.
  //
  // A limitation with no fix from in here, written down because it looks like a
  // bug in this handler: a hard reload (Ctrl+Shift+R, or DevTools' "empty cache
  // and hard reload") makes the browser bypass the service worker for the
  // navigation and its subresources entirely. Nothing below runs, so with no
  // line the shopkeeper gets the browser's own "no connection" page — and
  // reaching for a hard reload is exactly what someone does when the screen
  // looks wrong. There is no API a worker can call to opt back in. The cure is
  // operational: a plain reload (F5) does come through here and works offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (isShell(res)) return networkShell(res)
          // The line answered, but not with HTML at all: a 404, a 502, an opaque
          // redirect to a portal. The cached shell is worth more than any of
          // them. With nothing cached the server's own answer is the honest one,
          // and it is also the only way the owner ever gets to see a portal's
          // login form and sign in to the wifi.
          return caches.match('/index.html').then((hit) => hit || res)
        })
        .catch(() => caches.match('/index.html').then((hit) => hit || offlinePage())),
    )
    return
  }

  // Fingerprinted build output can never change behind its URL, so the cache
  // is always right and always faster.
  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(
      caches.match(req).then((hit) => {
        if (hit) return hit
        return fetch(req)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone()
              caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {})
            }
            return res
          })
          // A definite answer on a miss. Letting the rejection through made
          // respondWith reject, which the browser reports as a bare network
          // error plus an unhandled rejection inside the worker — nothing that
          // names the file. A 504 whose body names the URL shows up in the
          // network panel as coming from the worker, so "the till went blank"
          // becomes one line in DevTools instead of guesswork.
          .catch(
            () =>
              new Response('offline: ' + url.pathname + ' is not in cache ' + CACHE, {
                status: 504,
                headers: {
                  'Content-Type': 'text/plain; charset=utf-8',
                  'Cache-Control': 'no-store',
                },
              }),
          )
      }),
    )
    return
  }

  // Everything else we serve ourselves (the icon, the manifest): show what is
  // cached at once, and quietly refresh it for next time.
  event.respondWith(
    caches.match(req).then((hit) => {
      const network = fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {})
          }
          return res
        })
        // Same reason as /assets above: with nothing cached and no line this
        // used to resolve to undefined, and respondWith(undefined) throws.
        .catch(
          () =>
            hit ||
            new Response('offline: ' + url.pathname, {
              status: 504,
              headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' },
            }),
        )
      return hit || network
    }),
  )
})
`
}

export function shopServiceWorker(): Plugin {
  // The precache list mixes files Rollup emits (index.html, /assets/*) with
  // files Vite copies verbatim out of public/ (the manifest, the icon). The
  // version hash has to be able to read the bytes of both, so both roots are
  // captured here.
  let root = ''
  let publicDir = ''

  return {
    name: 'shop-service-worker',
    apply: 'build',
    configResolved(config) {
      root = config.root
      publicDir = config.publicDir
    },
    generateBundle(_options, bundle) {
      const files = Object.keys(bundle)
        .filter((name) => PRECACHE_EXT.test(name))
        // index.html is already in the fixed list below, under both of the
        // keys it is served as.
        .filter((name) => name !== 'index.html')
        .map((name) => `/${name}`)

      const precache = ['/', '/index.html', '/manifest.webmanifest', '/favicon.svg', ...files]

      /** The bytes actually served for one precached URL, or null if unreadable. */
      const contentOf = (url: string): string | Uint8Array | null => {
        // '/' and '/index.html' are the same document: netlify.toml rewrites
        // every path to index.html, which is why both are precache keys.
        const name = url === '/' ? 'index.html' : url.slice(1)
        const emitted = bundle[name]
        if (emitted) return emitted.type === 'chunk' ? emitted.code : emitted.source
        // public/ is copied straight into dist and never enters the bundle, and
        // index.html may not be in it either depending on whether Vite's own
        // html plugin has emitted it by the time this hook runs — so fall back
        // to the template on disk. An edit there is precisely the release the
        // old filename-only hash used to miss.
        for (const dir of [publicDir, root]) {
          if (!dir) continue
          try {
            return readFileSync(join(dir, name))
          } catch {
            /* not in this directory; try the next one */
          }
        }
        return null
      }

      const contents = precache.map(
        (url) => [url, contentOf(url)] as [string, string | Uint8Array | null],
      )
      const unreadable = contents.filter(([, body]) => body === null).map(([url]) => url)
      if (unreadable.length > 0) {
        // Worth a build warning on both counts: the version hash cannot see
        // changes to a file it cannot read, and install() now treats a missing
        // shell, chunk or stylesheet as fatal rather than shrugging it off.
        this.warn(
          `service worker: could not read ${unreadable.join(', ')} — not covered by the version hash`,
        )
      }

      const essential = bootFiles(bundle)
      if (essential.length === 0) {
        // Without a boot set, install() would treat only the shell as essential
        // and every script as optional — a worker that installs "successfully"
        // with no JavaScript in it. Loud, because the build still succeeds.
        this.warn(
          'service worker: no entry chunk found, so nothing but the shell is precached atomically',
        )
      }

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource(precache, contentVersion(contents), entryScript(bundle), essential),
      })
    },
  }
}

/**
 * Everything the first paint statically needs: the entry chunk, every chunk it
 * imports (transitively), and the stylesheets those pull in.
 *
 * Taken from Rollup's own graph rather than inferred from file extensions,
 * because the distinction that matters — static import versus dynamic import —
 * is invisible in a filename. `imports` holds only the static edges, so a
 * lazily-loaded route is correctly absent from this set even though it is a .js
 * file sitting in the same directory as the entry.
 *
 * @see isEssential in the generated worker for why the difference decides
 * whether one flaky fetch costs a shop its offline cache.
 */
function bootFiles(bundle: Record<string, BundleFile>): string[] {
  const entry = Object.values(bundle).find((f) => f.type === 'chunk' && f.isEntry)
  if (!entry) return []

  const out = new Set<string>()
  const walk = (fileName: string) => {
    const url = `/${fileName}`
    // Also the cycle guard: a chunk graph can contain them.
    if (out.has(url)) return
    out.add(url)
    const file = bundle[fileName]
    if (!file || file.type !== 'chunk') return
    for (const dep of file.imports ?? []) walk(dep)
    for (const css of file.viteMetadata?.importedCss ?? []) out.add(`/${css}`)
  }
  walk(entry.fileName)
  return [...out]
}

/** The entry chunk's URL, e.g. /assets/index-a1b2c3.js — see putShell(). */
/**
 * The parts of a Rollup output entry this plugin reads. Declared narrowly rather
 * than imported from rollup so the plugin keeps compiling across Vite majors,
 * where the exact output types have moved more than once.
 */
interface BundleFile {
  type: string
  fileName: string
  isEntry?: boolean
  /** Static imports only. Dynamic ones live in dynamicImports. @see bootFiles */
  imports?: string[]
  viteMetadata?: { importedCss?: Set<string> }
}

function entryScript(bundle: Record<string, BundleFile>): string {
  for (const file of Object.values(bundle)) {
    if (file.type === 'chunk' && file.isEntry) return `/${file.fileName}`
  }
  return ''
}

/**
 * The cache-busting version, taken from the CONTENT of everything precached.
 *
 * It used to be a djb2 hash of the filename list, which looks equivalent
 * because Vite fingerprints /assets/* — but a release that touched only
 * index.html, favicon.svg or manifest.webmanifest emitted a byte-identical
 * sw.js. No new worker, no cache rotation. A shop PC whose tab is never closed
 * then kept serving the old JavaScript out of the old cache while its reloads
 * pulled the new index.html off the network, and one page was running two
 * builds at once — which is the shape that produces bug reports nobody can
 * reproduce.
 *
 * Each URL is hashed alongside its bytes so a pure rename still rotates the
 * cache, and a file that cannot be read hashes as ABSENT rather than being
 * skipped: a file going missing has to change the version, not hide.
 */
function contentVersion(contents: Array<[string, string | Uint8Array | null]>): string {
  const h = createHash('sha256')
  for (const [url, body] of contents) {
    h.update(url)
    h.update('\0')
    h.update(body === null ? 'ABSENT' : body)
    h.update('\0')
  }
  // Twelve hex characters is ~48 bits: far more than enough that two builds
  // never collide, short enough to read in a cache name.
  return h.digest('hex').slice(0, 12)
}

/**
 * A JavaScript string literal for the generated worker, with every non-ASCII
 * character escaped. The offline page carries Arabic; escaping it keeps sw.js
 * pure ASCII so no host serving it under the wrong charset can mangle it. The
 * Response built from it declares UTF-8, so the page still renders.
 */
function jsLiteral(text: string): string {
  const json = JSON.stringify(text)
  let out = ''
  // Escaped per UTF-16 code unit, so a surrogate pair comes out as two valid
  // escapes rather than one broken one.
  for (let i = 0; i < json.length; i += 1) {
    const code = json.charCodeAt(i)
    out += code > 126 ? '\\u' + code.toString(16).padStart(4, '0') : json[i]
  }
  return out
}
