import type { Plugin } from 'vite'

/**
 * Emits the shop's service worker at build time.
 *
 * Why one is needed at all: without a service worker the browser cannot fetch
 * index.html or the JavaScript chunks when the line is down, so with no
 * internet the owner does not get a degraded till — he gets the browser's
 * "no connection" page and cannot sell at all. Firestore's IndexedDB cache
 * only helps once the app is already running.
 *
 * It is written here rather than pulled from a plugin so there is no extra
 * dependency and nothing hidden: the file below is exactly what ships.
 */

/** Assets that are worth having before they are ever asked for. */
const PRECACHE_EXT = /\.(?:js|css|html|svg|png|webmanifest|woff2?)$/

function swSource(precache: string[], version: string): string {
  return `/* Generated by scripts/pwa.ts at build time — do not edit by hand. */
const VERSION = '${version}'
const CACHE = 'librairie-' + VERSION
const PRECACHE = ${JSON.stringify(precache, null, 2)}

self.addEventListener('install', (event) => {
  // Fetched one by one rather than with addAll, so a single 404 (a stale
  // filename, a blocked request) cannot leave the shop with no cache at all.
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: 'reload' })).catch(() => {}),
        ),
      ),
    ),
  )
  // Deliberately NO skipWaiting: a new version must not swap the JavaScript
  // under a sale that is halfway through. It takes over on the next full
  // load, or immediately when the owner accepts the update banner.
})

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return

  const url = new URL(req.url)

  // Everything Firebase is left completely alone. Firestore's transport is a
  // long-lived streaming channel with its own offline queue; putting a fetch
  // handler in front of it would at best cache nothing and at worst break the
  // stream and the write queue with it.
  if (url.origin !== self.location.origin) return

  // The page itself: try the network first so a deploy is picked up, and fall
  // back to the cached shell when there is no line. React Router owns the
  // routing once the shell is up, so /caisse and /stock work the same way.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone()
          caches.open(CACHE).then((c) => c.put('/index.html', copy))
          return res
        })
        .catch(() =>
          caches
            .match('/index.html')
            .then((hit) => hit || new Response('', { status: 504 })),
        ),
    )
    return
  }

  // Fingerprinted build output can never change behind its URL, so the cache
  // is always right and always faster.
  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            if (res.ok) {
              const copy = res.clone()
              caches.open(CACHE).then((c) => c.put(req, copy))
            }
            return res
          }),
      ),
    )
    return
  }

  // Everything else we serve ourselves (the icon, the manifest): show what is
  // cached at once, and quietly refresh it for next time.
  event.respondWith(
    caches.match(req).then((hit) => {
      const network = fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
          }
          return res
        })
        .catch(() => hit)
      return hit || network
    }),
  )
})
`
}

export function shopServiceWorker(): Plugin {
  return {
    name: 'shop-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const files = Object.keys(bundle)
        .filter((name) => PRECACHE_EXT.test(name))
        // index.html is cached under its own path by the navigation handler.
        .filter((name) => name !== 'index.html')
        .map((name) => `/${name}`)

      const precache = ['/', '/index.html', '/manifest.webmanifest', '/favicon.svg', ...files]

      // The cache name changes whenever the build output does, which is what
      // makes the browser install the new worker and drop the old cache.
      const version = hash(precache.join('|'))

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource(precache, version),
      })
    },
  }
}

/** Small stable hash — only needs to change when the file list changes. */
function hash(input: string): string {
  let h = 5381
  for (let i = 0; i < input.length; i += 1) h = ((h << 5) + h + input.charCodeAt(i)) >>> 0
  return h.toString(36)
}
